<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir . '/themes/stasis';

return array(
    'Zend_' => array($vendorDir . '/themes/stasis/framework/thirdparty/Zend'),
    'SilverStripe\\' => array($vendorDir . '/themes/stasis/framework/src'),
);
